name: Get and Cache Dep
description: Get the dependencies (via npm) and cache them

runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      working-directory: ./custom-github-actions
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      working-directory: ./custom-github-actions
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
