name: Get and Cache Dep
description: Get the dependencies (via npm) and cache them

inputs:
  path:
    description: Path of working directory
    default: .
    required: false

outputs:
  used-cache:
    description: Whether cache was used
    value: ${{ steps.install-dep.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install-dep
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.path }}
      run: |
        npm ci
        echo "cache-hit=true" >> $GITHUB_OUTPUT
      shell: bash
