name: "Action Types and Event Filters"

on:
  pull_request:
    types:
        - opened
  workflow_dispatch:

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: events-deep-dive
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build