name: Practice Project One

on: [push]

jobs:
  lint:
      name: "Lint"
      runs-on: "ubuntu-latest"
      defaults:
        run:
          working-directory: practice-project-one
      steps:
        - name: "Checkout"
          uses: actions/checkout@v3
        - name: Setup Nodejs v18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run Lint
          run: npm run lint

  test:
      name: "Test"
      runs-on: "ubuntu-latest"
      needs: lint
      defaults:
        run:
          working-directory: practice-project-one
      steps:
        - name: "Checkout"
          uses: actions/checkout@v3
        - name: Setup Nodejs v18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run Tests
          run: npm run test

  build:
      name: "Build"
      runs-on: "ubuntu-latest"
      needs: [lint, test]
      defaults:
        run:
          working-directory: practice-project-one
      steps:
        - name: "Checkout"
          uses: actions/checkout@v3
        - name: Setup Nodejs v18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run Build
          run: npm run build