name: React Action Demo Workflow

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-action-demo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [test]
    defaults:
      run:
        working-directory: react-action-demo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
