name: Reusable Deploy Workflow

on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of build artifact
        type: string
        required: true
        default: dist
  # secrets:
    # some-secret:
      # required: false
    outputs:
      result:
        description: Deploy result
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  download_build:
    name: Download Build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Print artifact
        run: ls

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    steps:
      - name: deploying
        run:  echo "Deploying"
      - name: Result output
        id: step-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT