name: Use Reusable Deploy Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: controlling-workflow-and-job-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dep 
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ./controlling-workflow-and-job-execution/dist

  deploy:
    name: Deploy
    needs: [ build ]
    uses: ./.github/workflows/reusable-deploy-workflow.yml
    with:
       artifact-name: dist-files
  # secrets:
    #  some-secret: ${{ secrets.some-secret }}

  deploy_result:
    name: Deploy Result
    needs: [ deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Print results
        run: echo "${{ needs.deploy.outputs.result }}"